In [18]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt
import seaborn as sb
import plotly.express as px 
pd.set_option('display.max_columns', None)

In [47]:
df=pd.read_csv("mumbai_property_data_with_TS.csv")

In [20]:
df.head()

,ID,Property Type,Address Area,Amenities,Property Age,Carpet Area (sq.ft.),Super Buildup Rate (per sq.ft.),Built-Up Area (sq.ft.),Area as per Approved Plan (sq.ft.),Valuation Area (sq.ft.),Super Built-up Area (sq.ft.),Total Value (INR),No of Car Parks,Value of Car Park (INR),Final Value by Comparison Method (INR),Configuration,Condition,Landmark,Landmark Distance (KM),Last Sale Price (per sq.ft.),Last to Last Sale Price (per sq.ft.),Last Sale Year,Last to Last Sale Year,Property Name,Rate 2021 (per sq.ft.),Rate 2022 (per sq.ft.),Rate 2023 (per sq.ft.),Rate 2024 (per sq.ft.),Rate 2025 (per sq.ft.)
0,1,Residential,Borivali East,"Playground, Garden",15,709,21381.6,672,643,672,811,14368435.2,2,1000000,15368435.2,1BHK,Requires Renovation,Mall,1.1,35606,35606,2011,2011,River Hts,18570,19885,18681,20138,21381.6
1,2,Residential,Borivali East,"Playground, Parking, Gym, Lift",6,1110,27342.0,1089,1067,1089,1228,29775438.0,2,1000000,30775438.0,2BHK,Good,Park,4.8,32697,32697,2020,2020,Moon Hights,27538,28632,30545,32100,27342.0
2,3,Residential,Malad East,"Garden, Swimming Pool",10,1130,26906.0,1102,1072,1102,1298,29650412.0,2,1000000,30650412.0,2BHK,Fair,Park,3.8,24754,24754,2016,2016,Golden Vilas,24236,25576,23887,25103,26906.0
3,4,Residential,Juhu,"Playground, Garden, Lift",8,2166,57346.0,2120,2096,2120,2300,121573520.0,3,1500000,123073520.0,4BHK,Fair,School,1.2,53333,49114,2020,2018,Green Gdns,50907,54140,51208,54346,57346.0
4,5,Residential,Santacruz West,"Gym, Garden",3,2453,52827.0,2419,2403,2419,2649,127788513.0,1,500000,128288513.0,4BHK,New,School,1.1,52791,52791,2023,2023,Santacruz West Res Apt,54514,57170,59357,51011,52827.0

In [10]:
df.shape

(10000, 29)

In [11]:
df.isnull().sum()

ID                                        0
Property Type                             0
Address Area                              0
Amenities                                 0
Property Age                              0
Carpet Area (sq.ft.)                      0
Super Buildup Rate (per sq.ft.)           0
Built-Up Area (sq.ft.)                    0
Area as per Approved Plan (sq.ft.)        0
Valuation Area (sq.ft.)                   0
Super Built-up Area (sq.ft.)              0
Total Value (INR)                         0
No of Car Parks                           0
Value of Car Park (INR)                   0
Final Value by Comparison Method (INR)    0
Configuration                             0
Condition                                 0
Landmark                                  0
Landmark Distance (KM)                    0
Last Sale Price (per sq.ft.)              0
Last to Last Sale Price (per sq.ft.)      0
Last Sale Year                            0
Last to Last Sale Year                    0
Property Name                             0
Rate 2021 (per sq.ft.)                    0
Rate 2022 (per sq.ft.)                    0
Rate 2023 (per sq.ft.)                    0
Rate 2024 (per sq.ft.)                    0
Rate 2025 (per sq.ft.)                    0
dtype: int64

In [14]:
df.head()

,ID,Property Type,Address Area,Amenities,Property Age,Carpet Area (sq.ft.),Super Buildup Rate (per sq.ft.),Built-Up Area (sq.ft.),Area as per Approved Plan (sq.ft.),Valuation Area (sq.ft.),Super Built-up Area (sq.ft.),Total Value (INR),No of Car Parks,Value of Car Park (INR),Final Value by Comparison Method (INR),Configuration,Condition,Landmark,Landmark Distance (KM),Last Sale Price (per sq.ft.),Last to Last Sale Price (per sq.ft.),Last Sale Year,Last to Last Sale Year,Property Name,Rate 2021 (per sq.ft.),Rate 2022 (per sq.ft.),Rate 2023 (per sq.ft.),Rate 2024 (per sq.ft.),Rate 2025 (per sq.ft.)
0,1,Residential,Borivali East,"Playground, Garden",15,709,21381.6,672,643,672,811,14368435.2,2,1000000,15368435.2,1BHK,Requires Renovation,Mall,1.1,35606,35606,2011,2011,River Hts,18570,19885,18681,20138,21381.6
1,2,Residential,Borivali East,"Playground, Parking, Gym, Lift",6,1110,27342.0,1089,1067,1089,1228,29775438.0,2,1000000,30775438.0,2BHK,Good,Park,4.8,32697,32697,2020,2020,Moon Hights,27538,28632,30545,32100,27342.0
2,3,Residential,Malad East,"Garden, Swimming Pool",10,1130,26906.0,1102,1072,1102,1298,29650412.0,2,1000000,30650412.0,2BHK,Fair,Park,3.8,24754,24754,2016,2016,Golden Vilas,24236,25576,23887,25103,26906.0
3,4,Residential,Juhu,"Playground, Garden, Lift",8,2166,57346.0,2120,2096,2120,2300,121573520.0,3,1500000,123073520.0,4BHK,Fair,School,1.2,53333,49114,2020,2018,Green Gdns,50907,54140,51208,54346,57346.0
4,5,Residential,Santacruz West,"Gym, Garden",3,2453,52827.0,2419,2403,2419,2649,127788513.0,1,500000,128288513.0,4BHK,New,School,1.1,52791,52791,2023,2023,Santacruz West Res Apt,54514,57170,59357,51011,52827.0

In [13]:
df["Address Area"].value_counts()

Address Area
Santacruz West     966
Juhu               943
Andheri East       933
Bandra West        929
Goregaon West      919
Borivali East      914
Malad East         903
Malad West         899
Andheri West       886
Vile Parle East    875
Goregaon East      833
Name: count, dtype: int64

In [48]:
df_amenities = df['Amenities'].str.get_dummies(sep=',')

# Clean column names
df_amenities.columns = df_amenities.columns.str.strip().str.lower().str.replace(' ', '_')

# Merge back
df = pd.concat([df, df_amenities], axis=1)

In [49]:
df.drop(columns=['ID', 'Property Type','Property Name'], inplace=True)
df.head()

,Address Area,Amenities,Property Age,Carpet Area (sq.ft.),Super Buildup Rate (per sq.ft.),Built-Up Area (sq.ft.),Area as per Approved Plan (sq.ft.),Valuation Area (sq.ft.),Super Built-up Area (sq.ft.),Total Value (INR),No of Car Parks,Value of Car Park (INR),Final Value by Comparison Method (INR),Configuration,Condition,Landmark,Landmark Distance (KM),Last Sale Price (per sq.ft.),Last to Last Sale Price (per sq.ft.),Last Sale Year,Last to Last Sale Year,Rate 2021 (per sq.ft.),Rate 2022 (per sq.ft.),Rate 2023 (per sq.ft.),Rate 2024 (per sq.ft.),Rate 2025 (per sq.ft.),garden,gym,lift,parking,playground,swimming_pool,garden,gym,lift,parking,playground,swimming_pool
0,Borivali East,"Playground, Garden",15,709,21381.6,672,643,672,811,14368435.2,2,1000000,15368435.2,1BHK,Requires Renovation,Mall,1.1,35606,35606,2011,2011,18570,19885,18681,20138,21381.6,1,0,0,0,0,0,0,0,0,0,1,0
1,Borivali East,"Playground, Parking, Gym, Lift",6,1110,27342.0,1089,1067,1089,1228,29775438.0,2,1000000,30775438.0,2BHK,Good,Park,4.8,32697,32697,2020,2020,27538,28632,30545,32100,27342.0,0,1,1,1,0,0,0,0,0,0,1,0
2,Malad East,"Garden, Swimming Pool",10,1130,26906.0,1102,1072,1102,1298,29650412.0,2,1000000,30650412.0,2BHK,Fair,Park,3.8,24754,24754,2016,2016,24236,25576,23887,25103,26906.0,0,0,0,0,0,1,1,0,0,0,0,0
3,Juhu,"Playground, Garden, Lift",8,2166,57346.0,2120,2096,2120,2300,121573520.0,3,1500000,123073520.0,4BHK,Fair,School,1.2,53333,49114,2020,2018,50907,54140,51208,54346,57346.0,1,0,1,0,0,0,0,0,0,0,1,0
4,Santacruz West,"Gym, Garden",3,2453,52827.0,2419,2403,2419,2649,127788513.0,1,500000,128288513.0,4BHK,New,School,1.1,52791,52791,2023,2023,54514,57170,59357,51011,52827.0,1,0,0,0,0,0,0,1,0,0,0,0

In [50]:
property_effect = df.groupby('Address Area')['Super Buildup Rate (per sq.ft.)'].mean().sort_values()

print(property_effect.head())
print(property_effect.tail())

Address Area
Malad West       29159.849499
Malad East       30557.207420
Borivali East    31772.018928
Goregaon East    32984.046579
Goregaon West    33804.717410
Name: Super Buildup Rate (per sq.ft.), dtype: float64
Address Area
Vile Parle East    43082.152229
Andheri West       45484.758352
Bandra West        60043.157804
Santacruz West     60796.945963
Juhu               66625.574867
Name: Super Buildup Rate (per sq.ft.), dtype: float64

In [51]:
df.head()

,Address Area,Amenities,Property Age,Carpet Area (sq.ft.),Super Buildup Rate (per sq.ft.),Built-Up Area (sq.ft.),Area as per Approved Plan (sq.ft.),Valuation Area (sq.ft.),Super Built-up Area (sq.ft.),Total Value (INR),No of Car Parks,Value of Car Park (INR),Final Value by Comparison Method (INR),Configuration,Condition,Landmark,Landmark Distance (KM),Last Sale Price (per sq.ft.),Last to Last Sale Price (per sq.ft.),Last Sale Year,Last to Last Sale Year,Rate 2021 (per sq.ft.),Rate 2022 (per sq.ft.),Rate 2023 (per sq.ft.),Rate 2024 (per sq.ft.),Rate 2025 (per sq.ft.),garden,gym,lift,parking,playground,swimming_pool,garden,gym,lift,parking,playground,swimming_pool
0,Borivali East,"Playground, Garden",15,709,21381.6,672,643,672,811,14368435.2,2,1000000,15368435.2,1BHK,Requires Renovation,Mall,1.1,35606,35606,2011,2011,18570,19885,18681,20138,21381.6,1,0,0,0,0,0,0,0,0,0,1,0
1,Borivali East,"Playground, Parking, Gym, Lift",6,1110,27342.0,1089,1067,1089,1228,29775438.0,2,1000000,30775438.0,2BHK,Good,Park,4.8,32697,32697,2020,2020,27538,28632,30545,32100,27342.0,0,1,1,1,0,0,0,0,0,0,1,0
2,Malad East,"Garden, Swimming Pool",10,1130,26906.0,1102,1072,1102,1298,29650412.0,2,1000000,30650412.0,2BHK,Fair,Park,3.8,24754,24754,2016,2016,24236,25576,23887,25103,26906.0,0,0,0,0,0,1,1,0,0,0,0,0
3,Juhu,"Playground, Garden, Lift",8,2166,57346.0,2120,2096,2120,2300,121573520.0,3,1500000,123073520.0,4BHK,Fair,School,1.2,53333,49114,2020,2018,50907,54140,51208,54346,57346.0,1,0,1,0,0,0,0,0,0,0,1,0
4,Santacruz West,"Gym, Garden",3,2453,52827.0,2419,2403,2419,2649,127788513.0,1,500000,128288513.0,4BHK,New,School,1.1,52791,52791,2023,2023,54514,57170,59357,51011,52827.0,1,0,0,0,0,0,0,1,0,0,0,0

In [52]:
from category_encoders import TargetEncoder

te = TargetEncoder(cols=['Address Area'])
df['Address_Area_encoded'] = te.fit_transform(df['Address Area'], df['Super Buildup Rate (per sq.ft.)'])

In [53]:
config_map = {
    "1BHK": 1, "2BHK": 2, "3BHK": 3,
    "4BHK": 4, "Duplex": 5, "Penthouse": 6
}
df['Configuration_encoded'] = df['Configuration'].map(config_map)

In [54]:
condition_map = {
    "Requires Renovation": 1,
    "Good": 2,
    "Fair": 3,
    "New": 4
}
df['Condition_encoded'] = df['Condition'].map(condition_map)

In [55]:
df = pd.get_dummies(df, columns=['Landmark'], prefix='Landmark')

In [42]:
# Calculate ratio (last / first)
df["Trend_Ratio"] = df["Rate 2025 (per sq.ft.)"] / df["Rate 2021 (per sq.ft.)"]

# Normalize ratio into [0,1]
# Using logistic/sigmoid scaling so very high ratios don’t explode
df["Trend_Score"] = 1 / (1 + np.exp(-(df["Trend_Ratio"] - 1) * 5))

In [56]:
from sklearn.preprocessing import StandardScaler

# Columns to normalize (large values)
cols_to_normalize = [
    'Carpet Area (sq.ft.)',
    'Super Buildup Rate (per sq.ft.)',
    'Built-Up Area (sq.ft.)',
    'Area as per Approved Plan (sq.ft.)',
    'Valuation Area (sq.ft.)',
    'Super Built-up Area (sq.ft.)',
    'Total Value (INR)',
    'Value of Car Park (INR)',
    'Final Value by Comparison Method (INR)',
    'Last Sale Price (per sq.ft.)',
    'Last to Last Sale Price (per sq.ft.)'
]

# Initialize scaler
scaler = StandardScaler()

# Fit-transform only on the selected columns
df[cols_to_normalize] = scaler.fit_transform(df[cols_to_normalize])

In [57]:
# List of columns to drop (already encoded or duplicated)
drop_cols = [
    "Amenities",
    "Address Area",
    "Configuration",
    "Condition",
    "Landmark Distance (KM)",
    "Rate 2021 (per sq.ft.)", "Rate 2022 (per sq.ft.)", 
    "Rate 2023 (per sq.ft.)", "Rate 2024 (per sq.ft.)", "Rate 2025 (per sq.ft.)"
]


# Drop unnecessary columns
df_cleaned = df.drop(columns=drop_cols, errors="ignore")

# Save to new CSV
df_cleaned.to_csv("cleaned_property_data.csv", index=False)