In [16]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [3]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=["id","Unnamed: 32"],inplace=True)

In [6]:
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=42)

In [7]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [8]:
x_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [9]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

In [10]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

#NUMPY ARRAYS TO TENSORS FOR PYTORCH

In [11]:
x_train_tensor=torch.from_numpy(x_train)
x_test_tensor=torch.from_numpy(x_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [12]:
x_train_tensor

tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]],
       dtype=torch.float64)

In [16]:
# DEFINING MODEL

In [33]:
class MySimpleNN():
  def __init__(self,x):
    self.weights=torch.rand(x.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)
  def forward(self,x):
    z=torch.matmul(x,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred
  def loss_function(self,y_pred,y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred))
    loss = loss.mean()
    return loss

##TRAINING PIPELINE

In [49]:
#create model
model=MySimpleNN(x_train_tensor)
model.weights

tensor([[0.6043],
        [0.8860],
        [0.2671],
        [0.7519],
        [0.7506],
        [0.6611],
        [0.6513],
        [0.8285],
        [0.6324],
        [0.7471],
        [0.0924],
        [0.9616],
        [0.0330],
        [0.8994],
        [0.0535],
        [0.4864],
        [0.3340],
        [0.8486],
        [0.0046],
        [0.0922],
        [0.6653],
        [0.8483],
        [0.5527],
        [0.9022],
        [0.7074],
        [0.0551],
        [0.3013],
        [0.3525],
        [0.9885],
        [0.8070]], dtype=torch.float64, requires_grad=True)

In [26]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [124]:
learning_rate=0.01
epochs=1000
model=MySimpleNN(x_train_tensor)
#define loop
for epoch in range(epochs):
  #forward pass
  y_pred=model.forward(x_train_tensor)

  # loss calculate
  loss=model.loss_function(y_pred,y_train_tensor)

  #backward pass
  loss.backward()

  #parameters update
  with torch.no_grad():
    model.weights-=learning_rate*model.weights.grad.data
    model.bias-=learning_rate*model.bias.grad.data

  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f"epoch {epoch+1} loss {loss.item()}")

epoch 1 loss 3.8072940018384767
epoch 2 loss 3.796092761574542
epoch 3 loss 3.784902459680437
epoch 4 loss 3.773723182626652
epoch 5 loss 3.762555018307547
epoch 6 loss 3.751398056046963
epoch 7 loss 3.7402523865978883
epoch 8 loss 3.7291181021524884
epoch 9 loss 3.7179952963508494
epoch 10 loss 3.7068420276528027
epoch 11 loss 3.6953439638534653
epoch 12 loss 3.6838582845944114
epoch 13 loss 3.6723560047830826
epoch 14 loss 3.660655921050254
epoch 15 loss 3.648907396141407
epoch 16 loss 3.6371721001238315
epoch 17 loss 3.625450151555698
epoch 18 loss 3.613741670684645
epoch 19 loss 3.6020284730239323
epoch 20 loss 3.59025419828576
epoch 21 loss 3.5784938172113834
epoch 22 loss 3.5667474581781713
epoch 23 loss 3.554952855176555
epoch 24 loss 3.543054326937611
epoch 25 loss 3.5311705033123033
epoch 26 loss 3.5193015231728677
epoch 27 loss 3.507447527189424
epoch 28 loss 3.4956086577808767
epoch 29 loss 3.4837097298807604
epoch 30 loss 3.4716705738027946
epoch 31 loss 3.4596290936906153
epoch 32 loss 3.4472999584496877
epoch 33 loss 3.434862083126045
epoch 34 loss 3.4224416819726358
epoch 35 loss 3.410038929428487
epoch 36 loss 3.397654002067139
epoch 37 loss 3.3852870785851343
epoch 38 loss 3.3729383398246835
epoch 39 loss 3.360548823226599
epoch 40 loss 3.3480282754854707
epoch 41 loss 3.3354372128637033
epoch 42 loss 3.322770788397742
epoch 43 loss 3.3101242516287157
epoch 44 loss 3.297488218056338
epoch 45 loss 3.284703780077725
epoch 46 loss 3.2719401297827866
epoch 47 loss 3.259197485614212
epoch 48 loss 3.246452556221705
epoch 49 loss 3.2335418076644364
epoch 50 loss 3.220653055031766
epoch 51 loss 3.207786532724608
epoch 52 loss 3.194920605619546
epoch 53 loss 3.1819233872289914
epoch 54 loss 3.1689491320522336
epoch 55 loss 3.1559980873947993
epoch 56 loss 3.143070503388931
epoch 57 loss 3.1301177896817727
epoch 58 loss 3.1169414198493577
epoch 59 loss 3.1035828389221334
epoch 60 loss 3.090249863629878
epoch 61 loss 3.076942778383056
epoch 62 loss 3.0636618709087875
epoch 63 loss 3.0504074322821864
epoch 64 loss 3.037134638372784
epoch 65 loss 3.023575072472777
epoch 66 loss 3.0098237850313336
epoch 67 loss 2.9961019576260934
epoch 68 loss 2.982409928233431
epoch 69 loss 2.9687480387498626
epoch 70 loss 2.9551166350465183
epoch 71 loss 2.941516066954601
epoch 72 loss 2.9279466882869505
epoch 73 loss 2.9144088568378677
epoch 74 loss 2.900902934395404
epoch 75 loss 2.887402494694065
epoch 76 loss 2.8735618244988
epoch 77 loss 2.8596388714003775
epoch 78 loss 2.8457508187036145
epoch 79 loss 2.8318980760878554
epoch 80 loss 2.818081057532254
epoch 81 loss 2.8043001812980792
epoch 82 loss 2.790555869877362
epoch 83 loss 2.776848549936628
epoch 84 loss 2.7631786522706165
epoch 85 loss 2.749546611712127
epoch 86 loss 2.7358831261697074
epoch 87 loss 2.7221017842641038
epoch 88 loss 2.708360052160283
epoch 89 loss 2.694658390388143
epoch 90 loss 2.6809972632838446
epoch 91 loss 2.667377138854407
epoch 92 loss 2.653798488667638
epoch 93 loss 2.6402617877123427
epoch 94 loss 2.6267675142591185
epoch 95 loss 2.6133161496908928
epoch 96 loss 2.5999081783591382
epoch 97 loss 2.5865440873959082
epoch 98 loss 2.57322436653325
epoch 99 loss 2.559949507914116
epoch 100 loss 2.546702064808342
epoch 101 loss 2.533234697723176
epoch 102 loss 2.5198148630732273
epoch 103 loss 2.506443081520137
epoch 104 loss 2.49311987520458
epoch 105 loss 2.4798457675164793
epoch 106 loss 2.4666212828124534
epoch 107 loss 2.453446946165922
epoch 108 loss 2.440323283073354
epoch 109 loss 2.427250819197631
epoch 110 loss 2.4142300800808476
epoch 111 loss 2.4012615908679646
epoch 112 loss 2.3883458760278677
epoch 113 loss 2.37548345908495
epoch 114 loss 2.3626748623448632
epoch 115 loss 2.3499206066317413
epoch 116 loss 2.3372212110345525
epoch 117 loss 2.3245771926598895
epoch 118 loss 2.3119890663971905
epoch 119 loss 2.299457344694655
epoch 120 loss 2.2869825373519053
epoch 121 loss 2.2745651513211693
epoch 122 loss 2.26220569053222
epoch 123 loss 2.2499046557237694
epoch 124 loss 2.2376625442981535
epoch 125 loss 2.2254798501889677
epoch 126 loss 2.213357063742789
epoch 127 loss 2.201294671619806
epoch 128 loss 2.1892931567057503
epoch 129 loss 2.1773529980359654
epoch 130 loss 2.1654746707339685
epoch 131 loss 2.1536586459565656
epoch 132 loss 2.1419053908480006
epoch 133 loss 2.130215368499406
epoch 134 loss 2.1185890379109
epoch 135 loss 2.1070268539555035
epoch 136 loss 2.095529267340685
epoch 137 loss 2.084096724566587
epoch 138 loss 2.0727296678771396
epoch 139 loss 2.061428535203561
epoch 140 loss 2.050138765986162
epoch 141 loss 2.038673422811585
epoch 142 loss 2.0272759302384364
epoch 143 loss 2.015819931808295
epoch 144 loss 2.004185133001054
epoch 145 loss 1.9923463163673383
epoch 146 loss 1.9805814746038601
epoch 147 loss 1.9688910945406055
epoch 148 loss 1.957275657552677
epoch 149 loss 1.9457356392574687
epoch 150 loss 1.9342715092186404
epoch 151 loss 1.9227985563457477
epoch 152 loss 1.9112165743510257
epoch 153 loss 1.8997132561293788
epoch 154 loss 1.8881818771661254
epoch 155 loss 1.8765574988988953
epoch 156 loss 1.865015094400486
epoch 157 loss 1.8535551341248044
epoch 158 loss 1.8421780789974629
epoch 159 loss 1.8308843798860477
epoch 160 loss 1.8196172352007136
epoch 161 loss 1.8082282404471846
epoch 162 loss 1.796925201898247
epoch 163 loss 1.7857085514836148
epoch 164 loss 1.7745787082854103
epoch 165 loss 1.7635360779463505
epoch 166 loss 1.7525799127060382
epoch 167 loss 1.7414227535729143
epoch 168 loss 1.7303556707192742
epoch 169 loss 1.7193790419803916
epoch 170 loss 1.7084932286956325
epoch 171 loss 1.6976985751434555
epoch 172 loss 1.6869954079675995
epoch 173 loss 1.6763840356298472
epoch 174 loss 1.6658647478753164
epoch 175 loss 1.655437815218964
epoch 176 loss 1.6451034884617006
epoch 177 loss 1.6348619982197514
epoch 178 loss 1.6247135544945457
epoch 179 loss 1.6146583462655302
epoch 180 loss 1.6046965411237526
epoch 181 loss 1.5948242251611107
epoch 182 loss 1.5847154497519027
epoch 183 loss 1.5747054991751799
epoch 184 loss 1.5647944704220396
epoch 185 loss 1.5549824351936512
epoch 186 loss 1.5452694397177775
epoch 187 loss 1.535655504622511
epoch 188 loss 1.5261406248730551
epoch 189 loss 1.516724769767068
epoch 190 loss 1.5074078829731428
epoch 191 loss 1.4981552964817977
epoch 192 loss 1.4886858707514479
epoch 193 loss 1.4793192872901744
epoch 194 loss 1.470055407941503
epoch 195 loss 1.4608940678961562
epoch 196 loss 1.4518350760213963
epoch 197 loss 1.4427998872106165
epoch 198 loss 1.4337058587153648
epoch 199 loss 1.4247173630577128
epoch 200 loss 1.415834097817861
epoch 201 loss 1.4070557340019474
epoch 202 loss 1.3983819165418618
epoch 203 loss 1.389812264784727
epoch 204 loss 1.3813463729839632
epoch 205 loss 1.3729838107592285
epoch 206 loss 1.364724123565809
epoch 207 loss 1.3565668331279233
epoch 208 loss 1.3485114378573269
epoch 209 loss 1.3405574132482694
epoch 210 loss 1.3327042122583415
epoch 211 loss 1.3249512656616542
epoch 212 loss 1.3172979823937054
epoch 213 loss 1.309743749873803
epoch 214 loss 1.302287934330836
epoch 215 loss 1.2949298811135708
epoch 216 loss 1.2876689150043452
epoch 217 loss 1.2805043405441852
epoch 218 loss 1.2734354423619296
epoch 219 loss 1.2664614855219611
epoch 220 loss 1.2595817158981173
epoch 221 loss 1.2527953605679985
epoch 222 loss 1.2461016282426567
epoch 223 loss 1.2394997097294342
epoch 224 loss 1.2329887784345435
epoch 225 loss 1.2265679909040397
epoch 226 loss 1.2202364874100458
epoch 227 loss 1.213993392580609
epoch 228 loss 1.207837816071727
epoch 229 loss 1.2017688532838422
epoch 230 loss 1.1957855861231887
epoch 231 loss 1.189887083799794
epoch 232 loss 1.1840724036663943
epoch 233 loss 1.1783405920907808
epoch 234 loss 1.17269068535995
epoch 235 loss 1.1671217106106524
epoch 236 loss 1.1616326867842424
epoch 237 loss 1.1562226255972785
epoch 238 loss 1.1508905325281409
epoch 239 loss 1.1456354078088269
epoch 240 loss 1.1404562474228446
epoch 241 loss 1.1353520441007867
epoch 242 loss 1.1303217883085617
epoch 243 loss 1.1253644692271674
epoch 244 loss 1.1204790757162109
epoch 245 loss 1.115664597258298
epoch 246 loss 1.110920024882218
epoch 247 loss 1.1062443520590772
epoch 248 loss 1.1016365755705375
epoch 249 loss 1.097095696345156
epoch 250 loss 1.092620720261266
epoch 251 loss 1.0882106589144551
epoch 252 loss 1.0838645303478025
epoch 253 loss 1.0795813597440092
epoch 254 loss 1.07536018007812
epoch 255 loss 1.0712000327302393
epoch 256 loss 1.0670999680578679
epoch 257 loss 1.0630590459280385
epoch 258 loss 1.0590763362080138
epoch 259 loss 1.0551509192163162
epoch 260 loss 1.0512818861328435
epoch 261 loss 1.0474683393695927
epoch 262 loss 1.0437093929018968
epoch 263 loss 1.0400041725607942
epoch 264 loss 1.0363518162873542
epoch 265 loss 1.0327514743493231
epoch 266 loss 1.029202309521442
epoch 267 loss 1.025703497229115
epoch 268 loss 1.0222542256572973
epoch 269 loss 1.0188536958246706
epoch 270 loss 1.015501121624345
epoch 271 loss 1.0121957298314472
epoch 272 loss 1.0089367600791572
epoch 273 loss 1.0057234648033682
epoch 274 loss 1.0025551091575367
epoch 275 loss 0.9994309708984783
epoch 276 loss 0.9963503402442062
epoch 277 loss 0.9933125197052151
epoch 278 loss 0.9903168238902467
epoch 279 loss 0.9873625792882845
epoch 280 loss 0.9844491240280552
epoch 281 loss 0.9815758076168538
epoch 282 loss 0.9787419906605169
epoch 283 loss 0.9759470445666647
epoch 284 loss 0.9731903512330843
epoch 285 loss 0.9704713027238097
epoch 286 loss 0.9677893009351861
epoch 287 loss 0.9651437572546497
epoch 288 loss 0.9625340922147732
epoch 289 loss 0.9599597351453414
epoch 290 loss 0.9574201238264852
epoch 291 loss 0.9549147041456487
epoch 292 loss 0.9524429297612734
epoch 293 loss 0.9500042617759863
epoch 294 loss 0.9475981684222733
epoch 295 loss 0.9452241247629883
epoch 296 loss 0.9428816124094236
epoch 297 loss 0.9405701192590297
epoch 298 loss 0.9382891392548102
epoch 299 loss 0.9360381721682373
epoch 300 loss 0.9338167234068137
epoch 301 loss 0.9316243038476261
epoch 302 loss 0.9294604296973474
epoch 303 loss 0.9273246223790608
epoch 304 loss 0.9252164084458178
epoch 305 loss 0.9231353195204622
epoch 306 loss 0.9210808922609115
epoch 307 loss 0.9190526683496781
epoch 308 loss 0.9170501945062767
epoch 309 loss 0.9150730225206217
epoch 310 loss 0.9131207093054923
epoch 311 loss 0.9111928169659163
epoch 312 loss 0.9092889128831179
epoch 313 loss 0.9074085698105232
epoch 314 loss 0.9055513659795259
epoch 315 loss 0.9037168852122789
epoch 316 loss 0.9019047170393317
epoch 317 loss 0.9001144568194925
epoch 318 loss 0.8983457058598235
epoch 319 loss 0.8965980715335804
epoch 320 loss 0.8948711673940719
epoch 321 loss 0.8931646132828523
epoch 322 loss 0.8914780354304479
epoch 323 loss 0.8898110665484431
epoch 324 loss 0.888163345911661
epoch 325 loss 0.886534519429546
epoch 326 loss 0.8849242397060142
epoch 327 loss 0.8833321660872477
epoch 328 loss 0.8817579646970471
epoch 329 loss 0.8802013084596472
epoch 330 loss 0.8786618771099097
epoch 331 loss 0.8771393571911221
epoch 332 loss 0.8756334420405584
epoch 333 loss 0.8741438317632967
epoch 334 loss 0.8726702331946846
epoch 335 loss 0.8712123598520128
epoch 336 loss 0.8697699318760622
epoch 337 loss 0.8683426759631149
epoch 338 loss 0.8669303252881837
epoch 339 loss 0.8655326194201496
epoch 340 loss 0.8641493042295078
epoch 341 loss 0.8627801317895575
epoch 342 loss 0.8614248602716246
epoch 343 loss 0.8600832538351139
epoch 344 loss 0.8587550825130991
epoch 345 loss 0.8574401220940165
epoch 346 loss 0.8561381540002138
epoch 347 loss 0.8548489651638737
epoch 348 loss 0.8535723479009522
epoch 349 loss 0.852308099783586
epoch 350 loss 0.8510560235115473
epoch 351 loss 0.8498159267831513
epoch 352 loss 0.8485876221660733
epoch 353 loss 0.8473709269684423
epoch 354 loss 0.8461656631105788
epoch 355 loss 0.8449716569976795
epoch 356 loss 0.8437887393937545
epoch 357 loss 0.8426167452970695
epoch 358 loss 0.8414555138172812
epoch 359 loss 0.8403048880545364
epoch 360 loss 0.8391647149806231
epoch 361 loss 0.8380348453223838
epoch 362 loss 0.8369151334474917
epoch 363 loss 0.8358054372526813
epoch 364 loss 0.8347056180545356
epoch 365 loss 0.8336155404829063
epoch 366 loss 0.8325350723769757
epoch 367 loss 0.8314640846840419
epoch 368 loss 0.8304024513610292
epoch 369 loss 0.8293500492787318
epoch 370 loss 0.828306758128801
epoch 371 loss 0.8272724603334601
epoch 372 loss 0.8262470409579338
epoch 373 loss 0.8252303876255642
epoch 374 loss 0.8242223904355785
epoch 375 loss 0.8232229418834841
epoch 376 loss 0.8222319367840367
epoch 377 loss 0.8212492721967405
epoch 378 loss 0.8202748473538236
epoch 379 loss 0.819308563590658
epoch 380 loss 0.8183503242785323
epoch 381 loss 0.8174000347597643
epoch 382 loss 0.8164576022850558
epoch 383 loss 0.8155229359530494
epoch 384 loss 0.8145959466520416
epoch 385 loss 0.8136765470037429
epoch 386 loss 0.8127646513090935
epoch 387 loss 0.8118601754960018
epoch 388 loss 0.8109630370690043
epoch 389 loss 0.8100731550607506
epoch 390 loss 0.8091904499852742
epoch 391 loss 0.808314843792969
epoch 392 loss 0.8074462598272392
epoch 393 loss 0.8065846227827591
epoch 394 loss 0.8057298586652631
epoch 395 loss 0.8048818947528475
epoch 396 loss 0.8040406595587094
epoch 397 loss 0.803206082795275
epoch 398 loss 0.8023780953396675
epoch 399 loss 0.8015566292004638
epoch 400 loss 0.8007416174856986
epoch 401 loss 0.7999329943720591
epoch 402 loss 0.7991306950752357
epoch 403 loss 0.7983346558213741
epoch 404 loss 0.7975448138195945
epoch 405 loss 0.7967611072355364
epoch 406 loss 0.7959834751658864
epoch 407 loss 0.795211857613844
epoch 408 loss 0.7944461954655105
epoch 409 loss 0.7936864304671373
epoch 410 loss 0.7929325052032135
epoch 411 loss 0.7921843630753668
epoch 412 loss 0.7914419482820295
epoch 413 loss 0.7907052057988424
epoch 414 loss 0.789974081359782
epoch 415 loss 0.7892485214389576
epoch 416 loss 0.7885284732330744
epoch 417 loss 0.787813884644515
epoch 418 loss 0.7871047042650343
epoch 419 loss 0.7864008813600237
epoch 420 loss 0.7857023658533352
epoch 421 loss 0.7850091083126373
epoch 422 loss 0.7843210599352787
epoch 423 loss 0.7836381725346433
epoch 424 loss 0.7829603985269753
epoch 425 loss 0.7822876909186525
epoch 426 loss 0.7816200032938916
epoch 427 loss 0.7809572898028678
epoch 428 loss 0.780299505150232
epoch 429 loss 0.7796466045840058
epoch 430 loss 0.7789985438848457
epoch 431 loss 0.7783552793556537
epoch 432 loss 0.7777167678115233
epoch 433 loss 0.7770829665700136
epoch 434 loss 0.776453833441722
epoch 435 loss 0.7758293267211608
epoch 436 loss 0.7752094051779176
epoch 437 loss 0.7745940280480828
epoch 438 loss 0.7739831550259453
epoch 439 loss 0.7733767462559328
epoch 440 loss 0.7727747623247975
epoch 441 loss 0.7721771642540328
epoch 442 loss 0.7715839134925074
epoch 443 loss 0.7709949719093183
epoch 444 loss 0.7704103017868433
epoch 445 loss 0.7698298658139914
epoch 446 loss 0.7692536270796456
epoch 447 loss 0.7686815490662798
epoch 448 loss 0.7681135956437556
epoch 449 loss 0.767549731063283
epoch 450 loss 0.7669899199515449
epoch 451 loss 0.7664341273049721
epoch 452 loss 0.7658823184841722
epoch 453 loss 0.7653344592084955
epoch 454 loss 0.7647905155507425
epoch 455 loss 0.7642504539320045
epoch 456 loss 0.7637142411166264
epoch 457 loss 0.7631818442072987
epoch 458 loss 0.7626532306402616
epoch 459 loss 0.7621283681806273
epoch 460 loss 0.7616072249178105
epoch 461 loss 0.7610897692610611
epoch 462 loss 0.7605759699351071
epoch 463 loss 0.7600657959758861
epoch 464 loss 0.7595592167263757
epoch 465 loss 0.7590562018325203
epoch 466 loss 0.7585567212392353
epoch 467 loss 0.7580607451865068
epoch 468 loss 0.7575682442055676
epoch 469 loss 0.7570791891151544
epoch 470 loss 0.756593551017842
epoch 471 loss 0.7561113012964522
epoch 472 loss 0.7556324116105337
epoch 473 loss 0.7551568538929115
epoch 474 loss 0.7546846003463052
epoch 475 loss 0.754215623440009
epoch 476 loss 0.7537498959066395
epoch 477 loss 0.7532873907389411
epoch 478 loss 0.7528280811866508
epoch 479 loss 0.7523719407534237
epoch 480 loss 0.7519189431938095
epoch 481 loss 0.7514690625102872
epoch 482 loss 0.7510222729503506
epoch 483 loss 0.7505785490036433
epoch 484 loss 0.7501378653991457
epoch 485 loss 0.7497001971024101
epoch 486 loss 0.7492655193128394
epoch 487 loss 0.7488338074610156
epoch 488 loss 0.7484050372060687
epoch 489 loss 0.7479791844330907
epoch 490 loss 0.747556225250593
epoch 491 loss 0.7471361359879988
epoch 492 loss 0.7467188931931837
epoch 493 loss 0.7463044736300468
epoch 494 loss 0.7458928542761254
epoch 495 loss 0.7454840123202433
epoch 496 loss 0.7450779251601969
epoch 497 loss 0.7446745704004745
epoch 498 loss 0.7442739258500111
epoch 499 loss 0.7438759695199774
epoch 500 loss 0.7434806796215988
epoch 501 loss 0.7430880345640077
epoch 502 loss 0.7426980129521281
epoch 503 loss 0.7423105935845887
epoch 504 loss 0.7419257554516672
epoch 505 loss 0.7415434777332613
epoch 506 loss 0.7411637397968931
epoch 507 loss 0.7407865211957348
epoch 508 loss 0.7404118016666671
epoch 509 loss 0.7400395611283619
epoch 510 loss 0.7396697796793916
epoch 511 loss 0.7393024375963636
epoch 512 loss 0.738937515332081
epoch 513 loss 0.7385749935137262
epoch 514 loss 0.7382148529410713
epoch 515 loss 0.7378570745847081
epoch 516 loss 0.7375016395843068
epoch 517 loss 0.7371485292468918
epoch 518 loss 0.7367977250451444
epoch 519 loss 0.7364492086157237
epoch 520 loss 0.7361029617576127
epoch 521 loss 0.7357589664304824
epoch 522 loss 0.7354172047530785
epoch 523 loss 0.7350776590016278
epoch 524 loss 0.7347403116082648
epoch 525 loss 0.7344051451594784
epoch 526 loss 0.7340721423945761
epoch 527 loss 0.7337412862041709
epoch 528 loss 0.7334125596286822
epoch 529 loss 0.733085945856859
epoch 530 loss 0.7327614282243197
epoch 531 loss 0.7324389902121085
epoch 532 loss 0.7321186154452709
epoch 533 loss 0.7318002876914476
epoch 534 loss 0.7314839908594796
epoch 535 loss 0.7311697089980389
epoch 536 loss 0.7308574262942661
epoch 537 loss 0.730547127072432
epoch 538 loss 0.7302387957926103
epoch 539 loss 0.7299324170493666
epoch 540 loss 0.7296279755704657
epoch 541 loss 0.7293254562155895
epoch 542 loss 0.7290248439750744
epoch 543 loss 0.7287261239686588
epoch 544 loss 0.7284292814442497
epoch 545 loss 0.7281343017767004
epoch 546 loss 0.7278411704666023
epoch 547 loss 0.7275498731390934
epoch 548 loss 0.7272603955426761
epoch 549 loss 0.7269727235480523
epoch 550 loss 0.7266868431469699
epoch 551 loss 0.726402740451082
epoch 552 loss 0.7261204016908206
epoch 553 loss 0.7258398132142808
epoch 554 loss 0.7255609614861191
epoch 555 loss 0.7252838330864644
epoch 556 loss 0.7250084147098382
epoch 557 loss 0.7247346931640918
epoch 558 loss 0.7244626553693488
epoch 559 loss 0.7241922883569659
epoch 560 loss 0.7239235792685003
epoch 561 loss 0.7236565153546904
epoch 562 loss 0.7233910839744481
epoch 563 loss 0.7231272725938602
epoch 564 loss 0.7228650687852032
epoch 565 loss 0.7226044602259666
epoch 566 loss 0.7223454346978873
epoch 567 loss 0.7220879800859957
epoch 568 loss 0.7218320843776707
epoch 569 loss 0.7215777356617045
epoch 570 loss 0.7213249221273792
epoch 571 loss 0.7210736320635518
epoch 572 loss 0.7208238538577486
epoch 573 loss 0.7205755759952709
epoch 574 loss 0.7203287870583088
epoch 575 loss 0.7200834757250648
epoch 576 loss 0.7198396307688856
epoch 577 loss 0.7195972410574056
epoch 578 loss 0.7193562955516968
epoch 579 loss 0.719116783305428
epoch 580 loss 0.7188786934640345
epoch 581 loss 0.718642015263894
epoch 582 loss 0.7184067380315127
epoch 583 loss 0.7181728511827188
epoch 584 loss 0.7179403442218663
epoch 585 loss 0.7177092067410429
epoch 586 loss 0.7174794284192917
epoch 587 loss 0.7172509990218344
epoch 588 loss 0.7170239083993089
epoch 589 loss 0.7167981464870089
epoch 590 loss 0.716573703304136
epoch 591 loss 0.7163505689530548
epoch 592 loss 0.7161287336185606
epoch 593 loss 0.715908187567149
epoch 594 loss 0.7156889211462978
epoch 595 loss 0.7154709247837528

In [59]:
model.bias

tensor([0.0013], dtype=torch.float64, requires_grad=True)

In [125]:
# model evaluate
with torch.no_grad():
  y_pred=model.forward(x_test_tensor)

  y_pred=(y_pred>1).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f"accuracy {accuracy}")

accuracy 0.6228070259094238

In [101]:
y_pred

tensor([[1.7841e-01],
        [9.7867e-01],
        [9.3381e-01],
        [3.5382e-01],
        [6.2453e-02],
        [1.0000e+00],
        [1.0000e+00],
        [9.5964e-01],
        [9.8913e-01],
        [7.6136e-05],
        [2.4115e-04],
        [8.4301e-01],
        [6.5707e-05],
        [9.9822e-01],
        [1.8288e-04],
        [1.0000e+00],
        [2.2016e-04],
        [3.4373e-04],
        [3.9395e-04],
        [9.9997e-01],
        [3.0356e-01],
        [8.6200e-03],
        [1.0000e+00],
        [6.4236e-06],
        [5.0933e-04],
        [5.2850e-01],
        [1.0823e-03],
        [1.9788e-02],
        [1.6026e-03],
        [1.0000e+00],
        [7.9707e-03],
        [7.9742e-05],
        [1.4450e-01],
        [4.0849e-04],
        [3.2169e-03],
        [1.7737e-03],
        [2.9186e-02],
        [2.1233e-03],
        [9.8329e-01],
        [4.9610e-03],
        [2.4465e-03],
        [9.9799e-01],
        [1.2196e-02],
        [4.2942e-04],
        [1.0306e-01],
        [1.4479e-02],
        [8.3230e-01],
        [1.7218e-04],
        [2.0990e-02],
        [8.9512e-03],
        [9.3544e-01],
        [1.0000e+00],
        [9.1882e-01],
        [7.0017e-01],
        [8.1972e-01],
        [2.9497e-04],
        [3.6526e-01],
        [1.0000e+00],
        [9.4225e-01],
        [4.8361e-04],
        [3.9925e-03],
        [1.0000e+00],
        [1.0000e+00],
        [2.4130e-04],
        [6.4460e-05],
        [2.7899e-02],
        [1.0000e+00],
        [1.0000e+00],
        [4.5544e-04],
        [4.4575e-01],
        [9.9986e-01],
        [9.9954e-01],
        [1.6979e-04],
        [9.9941e-01],
        [1.0728e-03],
        [4.7513e-02],
        [1.4007e-03],
        [7.6152e-01],
        [1.0948e-05],
        [3.2033e-01],
        [9.0487e-01],
        [1.3255e-05],
        [8.0266e-01],
        [1.0000e+00],
        [2.9018e-01],
        [1.0000e+00],
        [1.0000e+00],
        [1.0000e+00],
        [2.7082e-02],
        [1.3135e-02],
        [7.0987e-03],
        [1.1845e-01],
        [3.9439e-02],
        [1.8725e-06],
        [3.6176e-03],
        [4.6525e-02],
        [9.9874e-01],
        [1.0000e+00],
        [1.6831e-04],
        [9.9579e-01],
        [8.0760e-01],
        [9.7083e-06],
        [1.0000e+00],
        [9.9833e-01],
        [3.7457e-03],
        [1.9879e-02],
        [1.5929e-01],
        [1.0000e+00],
        [1.5445e-01],
        [4.1303e-04],
        [9.4044e-01],
        [2.1926e-03],
        [3.7608e-02],
        [1.0000e+00]], dtype=torch.float64)

In [99]:
(y_pred>0.9).float()

tensor([[0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.]])

In [73]:
(y_pred==y_test_tensor).float()

tensor([[1., 0., 0.,  ..., 1., 1., 0.],
        [0., 1., 1.,  ..., 0., 0., 1.],
        [0., 1., 1.,  ..., 0., 0., 1.],
        ...,
        [1., 0., 0.,  ..., 1., 1., 0.],
        [1., 0., 0.,  ..., 1., 1., 0.],
        [0., 1., 1.,  ..., 0., 0., 1.]])

In [36]:
class MySimpleNN(nn.Module):
  def __init__(self,input_size):
    super().__init__()
    self.linear = nn.Linear(input_size,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,x):
    out = self.linear(x)
    out = self.sigmoid(out)
    return out

In [37]:
# define loss function
loss_function= nn.BCELoss()

In [30]:
y_train_tensor.reshape(-1,1).float()

tensor([[0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.]])

In [38]:
learning_rate=0.01
epochs=1000
model=MySimpleNN(x_train_tensor.shape[1])
# define optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)
#define loop
for epoch in range(epochs):
  #forward pass
  y_pred=model(x_train_tensor.float())# no need to call model.forward(), just call model(), forward function will call automatically due to magic function
  # loss calculate
  loss=loss_function(y_pred,y_train_tensor.view(-1,1).float())#.view() fucntion is similar to .reshape()

  # clear gradients
  optimizer.zero_grad()

  #backward pass
  loss.backward()

  #parameters update
  optimizer.step()

  #zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  #print loss in each epoch
  print(f"epoch {epoch+1} loss {loss.item()}")

epoch 1 loss 0.8895871043205261
epoch 2 loss 0.8596075773239136
epoch 3 loss 0.8312550187110901
epoch 4 loss 0.8044849634170532
epoch 5 loss 0.7792441844940186
epoch 6 loss 0.7554711699485779
epoch 7 loss 0.7330985069274902
epoch 8 loss 0.7120538353919983
epoch 9 loss 0.6922624707221985
epoch 10 loss 0.6736487150192261
epoch 11 loss 0.6561375856399536
epoch 12 loss 0.6396557688713074
epoch 13 loss 0.6241327524185181
epoch 14 loss 0.6095014214515686
epoch 15 loss 0.5956981778144836
epoch 16 loss 0.5826634764671326
epoch 17 loss 0.5703417658805847
epoch 18 loss 0.5586812496185303
epoch 19 loss 0.5476341247558594
epoch 20 loss 0.5371562242507935
epoch 21 loss 0.5272067189216614
epoch 22 loss 0.5177482962608337
epoch 23 loss 0.5087463855743408
epoch 24 loss 0.500169575214386
epoch 25 loss 0.49198856949806213
epoch 26 loss 0.4841769337654114
epoch 27 loss 0.4767100214958191
epoch 28 loss 0.4695654511451721
epoch 29 loss 0.4627225399017334
epoch 30 loss 0.4561622440814972
epoch 31 loss 0.4498669505119324
epoch 32 loss 0.44382062554359436
epoch 33 loss 0.4380083680152893
epoch 34 loss 0.4324163496494293
epoch 35 loss 0.427031934261322
epoch 36 loss 0.4218432307243347
epoch 37 loss 0.41683945059776306
epoch 38 loss 0.41201040148735046
epoch 39 loss 0.4073467552661896
epoch 40 loss 0.4028396010398865
epoch 41 loss 0.39848095178604126
epoch 42 loss 0.3942631781101227
epoch 43 loss 0.39017921686172485
epoch 44 loss 0.38622236251831055
epoch 45 loss 0.38238656520843506
epoch 46 loss 0.3786659240722656
epoch 47 loss 0.37505507469177246
epoch 48 loss 0.37154895067214966
epoch 49 loss 0.3681428134441376
epoch 50 loss 0.3648321032524109
epoch 51 loss 0.3616125285625458
epoch 52 loss 0.3584803640842438
epoch 53 loss 0.3554316461086273
epoch 54 loss 0.3524630069732666
epoch 55 loss 0.34957098960876465
epoch 56 loss 0.3467525243759155
epoch 57 loss 0.3440046012401581
epoch 58 loss 0.34132441878318787
epoch 59 loss 0.33870935440063477
epoch 60 loss 0.33615684509277344
epoch 61 loss 0.33366450667381287
epoch 62 loss 0.331230103969574
epoch 63 loss 0.3288513720035553
epoch 64 loss 0.3265264928340912
epoch 65 loss 0.32425329089164734
epoch 66 loss 0.32203003764152527
epoch 67 loss 0.3198549449443817
epoch 68 loss 0.3177262842655182
epoch 69 loss 0.3156425654888153
epoch 70 loss 0.31360217928886414
epoch 71 loss 0.31160369515419006
epoch 72 loss 0.30964574217796326
epoch 73 loss 0.3077269196510315
epoch 74 loss 0.30584609508514404
epoch 75 loss 0.30400195717811584
epoch 76 loss 0.30219337344169617
epoch 77 loss 0.30041924118995667
epoch 78 loss 0.2986784279346466
epoch 79 loss 0.29697003960609436
epoch 80 loss 0.2952929735183716
epoch 81 loss 0.2936463952064514
epoch 82 loss 0.29202938079833984
epoch 83 loss 0.29044103622436523
epoch 84 loss 0.2888805568218231
epoch 85 loss 0.28734713792800903
epoch 86 loss 0.2858400344848633
epoch 87 loss 0.28435850143432617
epoch 88 loss 0.2829018533229828
epoch 89 loss 0.28146934509277344
epoch 90 loss 0.28006038069725037
epoch 91 loss 0.27867430448532104
epoch 92 loss 0.2773105502128601
epoch 93 loss 0.2759685218334198
epoch 94 loss 0.27464759349823
epoch 95 loss 0.27334725856781006
epoch 96 loss 0.27206704020500183
epoch 97 loss 0.27080634236335754
epoch 98 loss 0.26956474781036377
epoch 99 loss 0.2683417797088623
epoch 100 loss 0.26713693141937256
epoch 101 loss 0.2659497857093811
epoch 102 loss 0.2647799551486969
epoch 103 loss 0.26362699270248413
epoch 104 loss 0.26249054074287415
epoch 105 loss 0.26137015223503113
epoch 106 loss 0.2602654695510864
epoch 107 loss 0.2591761350631714
epoch 108 loss 0.2581019103527069
epoch 109 loss 0.25704225897789
epoch 110 loss 0.255996972322464
epoch 111 loss 0.25496572256088257
epoch 112 loss 0.2539481818675995
epoch 113 loss 0.25294408202171326
epoch 114 loss 0.2519530951976776
epoch 115 loss 0.25097498297691345
epoch 116 loss 0.2500094175338745
epoch 117 loss 0.24905617535114288
epoch 118 loss 0.24811497330665588
epoch 119 loss 0.24718564748764038
epoch 120 loss 0.24626781046390533
epoch 121 loss 0.245361328125
epoch 122 loss 0.24446596205234528
epoch 123 loss 0.24358148872852325
epoch 124 loss 0.24270762503147125
epoch 125 loss 0.24184425175189972
epoch 126 loss 0.24099113047122955
epoch 127 loss 0.24014803767204285
epoch 128 loss 0.23931482434272766
epoch 129 loss 0.2384912669658661
epoch 130 loss 0.2376772165298462
epoch 131 loss 0.23687246441841125
epoch 132 loss 0.23607684671878815
epoch 133 loss 0.23529021441936493
epoch 134 loss 0.2345123440027237
epoch 135 loss 0.2337431162595749
epoch 136 loss 0.23298239707946777
epoch 137 loss 0.23222999274730682
epoch 138 loss 0.2314857840538025
epoch 139 loss 0.23074962198734283
epoch 140 loss 0.23002132773399353
epoch 141 loss 0.22930081188678741
epoch 142 loss 0.22858792543411255
epoch 143 loss 0.2278825342655182
epoch 144 loss 0.2271845042705536
epoch 145 loss 0.2264937162399292
epoch 146 loss 0.22581003606319427
epoch 147 loss 0.22513337433338165
epoch 148 loss 0.2244635969400406
epoch 149 loss 0.22380055487155914
epoch 150 loss 0.22314415872097015
epoch 151 loss 0.22249439358711243
epoch 152 loss 0.22185099124908447
epoch 153 loss 0.22121398150920868
epoch 154 loss 0.22058320045471191
epoch 155 loss 0.21995852887630463
epoch 156 loss 0.21933995187282562
epoch 157 loss 0.2187272608280182
epoch 158 loss 0.2181204855442047
epoch 159 loss 0.21751943230628967
epoch 160 loss 0.21692407131195068
epoch 161 loss 0.21633431315422058
epoch 162 loss 0.215750053524971
epoch 163 loss 0.2151711881160736
epoch 164 loss 0.214597687125206
epoch 165 loss 0.214029461145401
epoch 166 loss 0.21346642076969147
epoch 167 loss 0.21290844678878784
epoch 168 loss 0.21235550940036774
epoch 169 loss 0.21180759370326996
epoch 170 loss 0.211264505982399
epoch 171 loss 0.21072624623775482
epoch 172 loss 0.2101927399635315
epoch 173 loss 0.20966391265392303
epoch 174 loss 0.20913968980312347
epoch 175 loss 0.20862004160881042
epoch 176 loss 0.20810486376285553
epoch 177 loss 0.207594096660614
epoch 178 loss 0.20708772540092468
epoch 179 loss 0.2065856158733368
epoch 180 loss 0.20608776807785034
epoch 181 loss 0.20559412240982056
epoch 182 loss 0.20510458946228027
epoch 183 loss 0.20461910963058472
epoch 184 loss 0.2041376829147339
epoch 185 loss 0.20366021990776062
epoch 186 loss 0.20318664610385895
epoch 187 loss 0.20271697640419006
epoch 188 loss 0.20225107669830322
epoch 189 loss 0.20178896188735962
epoch 190 loss 0.2013305276632309
epoch 191 loss 0.20087578892707825
epoch 192 loss 0.2004246711730957
epoch 193 loss 0.1999770998954773
epoch 194 loss 0.19953307509422302
epoch 195 loss 0.1990925371646881
epoch 196 loss 0.1986554116010666
epoch 197 loss 0.19822169840335846
epoch 198 loss 0.19779135286808014
epoch 199 loss 0.19736430048942566
epoch 200 loss 0.19694052636623383
epoch 201 loss 0.19651997089385986
epoch 202 loss 0.1961025893688202
epoch 203 loss 0.195688396692276
epoch 204 loss 0.19527731835842133
epoch 205 loss 0.1948692947626114
epoch 206 loss 0.19446434080600739
epoch 207 loss 0.19406235218048096
epoch 208 loss 0.1936633437871933
epoch 209 loss 0.19326727092266083
epoch 210 loss 0.19287408888339996
epoch 211 loss 0.1924838125705719
epoch 212 loss 0.1920962929725647
epoch 213 loss 0.1917116343975067
epoch 214 loss 0.1913297325372696
epoch 215 loss 0.19095054268836975
epoch 216 loss 0.19057407975196838
epoch 217 loss 0.19020026922225952
epoch 218 loss 0.18982911109924316
epoch 219 loss 0.18946059048175812
epoch 220 loss 0.18909458816051483
epoch 221 loss 0.18873117864131927
epoch 222 loss 0.18837028741836548
epoch 223 loss 0.18801191449165344
epoch 224 loss 0.1876559853553772
epoch 225 loss 0.18730252981185913
epoch 226 loss 0.18695145845413208
epoch 227 loss 0.18660278618335724
epoch 228 loss 0.18625648319721222
epoch 229 loss 0.18591251969337463
epoch 230 loss 0.1855708658695221
epoch 231 loss 0.18523147702217102
epoch 232 loss 0.1848943680524826
epoch 233 loss 0.18455949425697327
epoch 234 loss 0.1842268407344818
epoch 235 loss 0.18389637768268585
epoch 236 loss 0.183568075299263
epoch 237 loss 0.18324196338653564
epoch 238 loss 0.18291793763637543
epoch 239 loss 0.18259599804878235
epoch 240 loss 0.1822761595249176
epoch 241 loss 0.18195840716362
epoch 242 loss 0.18164265155792236
epoch 243 loss 0.1813289225101471
epoch 244 loss 0.181017205119133
epoch 245 loss 0.1807074397802353
epoch 246 loss 0.18039962649345398
epoch 247 loss 0.18009378015995026
epoch 248 loss 0.17978981137275696
epoch 249 loss 0.17948777973651886
epoch 250 loss 0.1791875958442688
epoch 251 loss 0.17888931930065155
epoch 252 loss 0.17859286069869995
epoch 253 loss 0.17829817533493042
epoch 254 loss 0.17800533771514893
epoch 255 loss 0.1777142882347107
epoch 256 loss 0.17742501199245453
epoch 257 loss 0.17713746428489685
epoch 258 loss 0.17685167491436005
epoch 259 loss 0.17656759917736053
epoch 260 loss 0.17628523707389832
epoch 261 loss 0.1760045439004898
epoch 262 loss 0.1757255345582962
epoch 263 loss 0.1754481941461563
epoch 264 loss 0.17517244815826416
epoch 265 loss 0.17489834129810333
epoch 266 loss 0.17462587356567383
epoch 267 loss 0.17435497045516968
epoch 268 loss 0.17408564686775208
epoch 269 loss 0.17381787300109863
epoch 270 loss 0.17355169355869293
epoch 271 loss 0.17328700423240662
epoch 272 loss 0.17302386462688446
epoch 273 loss 0.17276223003864288
epoch 274 loss 0.1725020557641983
epoch 275 loss 0.1722433865070343
epoch 276 loss 0.1719861775636673
epoch 277 loss 0.1717304289340973
epoch 278 loss 0.1714761108160019
epoch 279 loss 0.1712232083082199
epoch 280 loss 0.17097175121307373
epoch 281 loss 0.17072166502475739
epoch 282 loss 0.17047296464443207
epoch 283 loss 0.17022566497325897
epoch 284 loss 0.16997969150543213
epoch 285 loss 0.1697351038455963
epoch 286 loss 0.16949184238910675
epoch 287 loss 0.16924993693828583
epoch 288 loss 0.16900932788848877
epoch 289 loss 0.16877000033855438
epoch 290 loss 0.16853198409080505
epoch 291 loss 0.1682952642440796
epoch 292 loss 0.1680598109960556
epoch 293 loss 0.1678255796432495
epoch 294 loss 0.16759264469146729
epoch 295 loss 0.16736094653606415
epoch 296 loss 0.1671304553747177
epoch 297 loss 0.16690117120742798
epoch 298 loss 0.16667310893535614
epoch 299 loss 0.166446253657341
epoch 300 loss 0.16622059047222137
epoch 301 loss 0.16599608957767487
epoch 302 loss 0.16577278077602386
epoch 303 loss 0.1655506044626236
epoch 304 loss 0.16532956063747406
epoch 305 loss 0.16510970890522003
epoch 306 loss 0.16489093005657196
epoch 307 loss 0.16467328369617462
epoch 308 loss 0.16445676982402802
epoch 309 loss 0.16424134373664856
epoch 310 loss 0.16402700543403625
epoch 311 loss 0.1638137698173523
epoch 312 loss 0.1636015772819519
epoch 313 loss 0.16339047253131866
epoch 314 loss 0.1631804257631302
epoch 315 loss 0.1629714071750641
epoch 316 loss 0.16276346147060394
epoch 317 loss 0.16255654394626617
epoch 318 loss 0.1623506098985672
epoch 319 loss 0.16214574873447418
epoch 320 loss 0.16194184124469757
epoch 321 loss 0.16173896193504333
epoch 322 loss 0.1615370661020279
epoch 323 loss 0.16133615374565125
epoch 324 loss 0.16113623976707458
epoch 325 loss 0.16093726456165314
epoch 326 loss 0.16073927283287048
epoch 327 loss 0.16054221987724304
epoch 328 loss 0.1603461503982544
epoch 329 loss 0.16015097498893738
epoch 330 loss 0.15995673835277557
epoch 331 loss 0.15976344048976898
epoch 332 loss 0.15957105159759521
epoch 333 loss 0.15937954187393188
epoch 334 loss 0.15918900072574615
epoch 335 loss 0.15899930894374847
epoch 336 loss 0.15881052613258362
epoch 337 loss 0.158622607588768
epoch 338 loss 0.15843556821346283
epoch 339 loss 0.15824942290782928
epoch 340 loss 0.1580640971660614
epoch 341 loss 0.15787966549396515
epoch 342 loss 0.15769608318805695
epoch 343 loss 0.1575133502483368
epoch 344 loss 0.1573314219713211
epoch 345 loss 0.15715034306049347
epoch 346 loss 0.1569700986146927
epoch 347 loss 0.15679064393043518
epoch 348 loss 0.15661205351352692
epoch 349 loss 0.15643420815467834
epoch 350 loss 0.15625721216201782
epoch 351 loss 0.15608100593090057
epoch 352 loss 0.1559055894613266
epoch 353 loss 0.1557309329509735
epoch 354 loss 0.1555570811033249
epoch 355 loss 0.15538397431373596
epoch 356 loss 0.1552116572856903
epoch 357 loss 0.15504010021686554
epoch 358 loss 0.15486928820610046
epoch 359 loss 0.15469922125339508
epoch 360 loss 0.15452991425991058
epoch 361 loss 0.15436135232448578
epoch 362 loss 0.15419350564479828
epoch 363 loss 0.15402638912200928
epoch 364 loss 0.15386003255844116
epoch 365 loss 0.15369436144828796
epoch 366 loss 0.15352940559387207
epoch 367 loss 0.15336516499519348
epoch 368 loss 0.1532016396522522
epoch 369 loss 0.15303881466388702
epoch 370 loss 0.15287669003009796
epoch 371 loss 0.15271520614624023
epoch 372 loss 0.152554452419281
epoch 373 loss 0.1523943841457367
epoch 374 loss 0.15223495662212372
epoch 375 loss 0.15207622945308685
epoch 376 loss 0.15191815793514252
epoch 377 loss 0.1517607420682907
epoch 378 loss 0.15160399675369263
epoch 379 loss 0.15144789218902588
epoch 380 loss 0.15129247307777405
epoch 381 loss 0.15113765001296997
epoch 382 loss 0.15098348259925842
epoch 383 loss 0.1508299559354782
epoch 384 loss 0.15067707002162933
epoch 385 loss 0.1505247801542282
epoch 386 loss 0.15037313103675842
epoch 387 loss 0.15022210776805878
epoch 388 loss 0.15007169544696808
epoch 389 loss 0.14992190897464752
epoch 390 loss 0.14977268874645233
epoch 391 loss 0.14962410926818848
epoch 392 loss 0.14947612583637238
epoch 393 loss 0.14932870864868164
epoch 394 loss 0.14918188750743866
epoch 395 loss 0.14903567731380463
epoch 396 loss 0.14889004826545715
epoch 397 loss 0.14874498546123505
epoch 398 loss 0.1486005038022995
epoch 399 loss 0.1484566032886505
epoch 400 loss 0.1483132541179657
epoch 401 loss 0.14817045629024506
epoch 402 loss 0.14802822470664978
epoch 403 loss 0.14788657426834106
epoch 404 loss 0.14774549007415771
epoch 405 loss 0.14760491251945496
epoch 406 loss 0.14746491611003876
epoch 407 loss 0.14732544124126434
epoch 408 loss 0.1471865177154541
epoch 409 loss 0.14704811573028564
epoch 410 loss 0.14691026508808136
epoch 411 loss 0.14677293598651886
epoch 412 loss 0.14663612842559814
epoch 413 loss 0.1464998573064804
epoch 414 loss 0.14636407792568207
epoch 415 loss 0.1462288498878479
epoch 416 loss 0.14609411358833313
epoch 417 loss 0.14595989882946014
epoch 418 loss 0.14582619071006775
epoch 419 loss 0.14569297432899475
epoch 420 loss 0.14556027948856354
epoch 421 loss 0.14542804658412933
epoch 422 loss 0.1452963501214981
epoch 423 loss 0.14516513049602509
epoch 424 loss 0.14503438770771027
epoch 425 loss 0.14490413665771484
epoch 426 loss 0.14477437734603882
epoch 427 loss 0.1446451097726822
epoch 428 loss 0.14451628923416138
epoch 429 loss 0.14438793063163757
epoch 430 loss 0.14426007866859436
epoch 431 loss 0.14413267374038696
epoch 432 loss 0.14400576055049896
epoch 433 loss 0.14387927949428558
epoch 434 loss 0.1437532752752304
epoch 435 loss 0.14362773299217224
epoch 436 loss 0.1435026377439499
epoch 437 loss 0.14337798953056335
epoch 438 loss 0.14325378835201263
epoch 439 loss 0.14313006401062012
epoch 440 loss 0.14300674200057983
epoch 441 loss 0.14288386702537537
epoch 442 loss 0.1427614539861679
epoch 443 loss 0.14263945817947388
epoch 444 loss 0.14251790940761566
epoch 445 loss 0.14239679276943207
epoch 446 loss 0.1422760784626007
epoch 447 loss 0.14215582609176636
epoch 448 loss 0.14203599095344543
epoch 449 loss 0.14191655814647675
epoch 450 loss 0.14179754257202148
epoch 451 loss 0.14167895913124084
epoch 452 loss 0.14156079292297363
epoch 453 loss 0.14144302904605865
epoch 454 loss 0.1413256675004959
epoch 455 loss 0.1412087231874466
epoch 456 loss 0.1410921812057495
epoch 457 loss 0.14097605645656586
epoch 458 loss 0.14086030423641205
epoch 459 loss 0.14074495434761047
epoch 460 loss 0.14063000679016113
epoch 461 loss 0.14051546156406403
epoch 462 loss 0.14040128886699677
epoch 463 loss 0.14028753340244293
epoch 464 loss 0.14017413556575775
epoch 465 loss 0.1400611251592636
epoch 466 loss 0.1399485170841217
epoch 467 loss 0.13983626663684845
epoch 468 loss 0.13972441852092743
epoch 469 loss 0.13961291313171387
epoch 470 loss 0.13950181007385254
epoch 471 loss 0.13939106464385986
epoch 472 loss 0.13928069174289703
epoch 473 loss 0.13917070627212524
epoch 474 loss 0.1390610635280609
epoch 475 loss 0.13895180821418762
epoch 476 loss 0.1388428956270218
epoch 477 loss 0.1387343555688858
epoch 478 loss 0.13862615823745728
epoch 479 loss 0.1385183185338974
epoch 480 loss 0.13841083645820618
epoch 481 loss 0.1383036971092224
epoch 482 loss 0.1381969302892685
epoch 483 loss 0.13809049129486084
epoch 484 loss 0.13798442482948303
epoch 485 loss 0.1378786712884903
epoch 486 loss 0.1377732753753662
epoch 487 loss 0.13766822218894958
epoch 488 loss 0.13756348192691803
epoch 489 loss 0.13745911419391632
epoch 490 loss 0.13735508918762207
epoch 491 loss 0.1372513622045517
epoch 492 loss 0.13714797794818878
epoch 493 loss 0.13704493641853333
epoch 494 loss 0.13694223761558533
epoch 495 loss 0.1368398368358612
epoch 496 loss 0.13673777878284454
epoch 497 loss 0.13663601875305176
epoch 498 loss 0.13653460144996643
epoch 499 loss 0.13643349707126617
epoch 500 loss 0.13633272051811218
epoch 501 loss 0.13623225688934326
epoch 502 loss 0.1361321061849594
epoch 503 loss 0.13603225350379944
epoch 504 loss 0.13593274354934692
epoch 505 loss 0.1358335167169571
epoch 506 loss 0.13573460280895233
epoch 507 loss 0.13563601672649384
epoch 508 loss 0.13553771376609802
epoch 509 loss 0.13543973863124847
epoch 510 loss 0.13534203171730042
epoch 511 loss 0.13524466753005981
epoch 512 loss 0.1351475715637207
epoch 513 loss 0.13505078852176666
epoch 514 loss 0.1349543035030365
epoch 515 loss 0.13485810160636902
epoch 516 loss 0.13476218283176422
epoch 517 loss 0.1346665769815445
epoch 518 loss 0.13457125425338745
epoch 519 loss 0.1344762146472931
epoch 520 loss 0.1343814730644226
epoch 521 loss 0.1342870146036148
epoch 522 loss 0.13419285416603088
epoch 523 loss 0.13409893214702606
epoch 524 loss 0.1340053379535675
epoch 525 loss 0.13391201198101044
epoch 526 loss 0.13381896913051605
epoch 527 loss 0.13372619450092316
epoch 528 loss 0.13363368809223175
epoch 529 loss 0.13354146480560303
epoch 530 loss 0.133449524641037
epoch 531 loss 0.13335783779621124
epoch 532 loss 0.13326644897460938
epoch 533 loss 0.1331753134727478
epoch 534 loss 0.13308444619178772
epoch 535 loss 0.13299384713172913
epoch 536 loss 0.13290350139141083
epoch 537 loss 0.1328134536743164
epoch 538 loss 0.1327236294746399
epoch 539 loss 0.13263408839702606
epoch 540 loss 0.13254481554031372
epoch 541 loss 0.13245578110218048
epoch 542 loss 0.13236701488494873
epoch 543 loss 0.13227850198745728
epoch 544 loss 0.1321902573108673
epoch 545 loss 0.13210225105285645
epoch 546 loss 0.13201449811458588
epoch 547 loss 0.1319270133972168
epoch 548 loss 0.13183976709842682
epoch 549 loss 0.13175278902053833
epoch 550 loss 0.13166603446006775
epoch 551 loss 0.13157953321933746
epoch 552 loss 0.13149328529834747
epoch 553 loss 0.13140727579593658
epoch 554 loss 0.13132153451442719
epoch 555 loss 0.1312360018491745
epoch 556 loss 0.1311507225036621
epoch 557 loss 0.13106568157672882
epoch 558 loss 0.13098089396953583
epoch 559 loss 0.13089632987976074
epoch 560 loss 0.13081200420856476
epoch 561 loss 0.13072791695594788
epoch 562 loss 0.1306440681219101
epoch 563 loss 0.13056044280529022
epoch 564 loss 0.13047707080841064
epoch 565 loss 0.13039390742778778
epoch 566 loss 0.13031096756458282
epoch 567 loss 0.13022829592227936
epoch 568 loss 0.1301458179950714
epoch 569 loss 0.13006359338760376
epoch 570 loss 0.12998157739639282
epoch 571 loss 0.1298997849225998
epoch 572 loss 0.12981821596622467
epoch 573 loss 0.12973688542842865
epoch 574 loss 0.12965577840805054
epoch 575 loss 0.12957488000392914
epoch 576 loss 0.12949420511722565
epoch 577 loss 0.12941375374794006
epoch 578 loss 0.1293335109949112
epoch 579 loss 0.12925349175930023
epoch 580 loss 0.12917369604110718
epoch 581 loss 0.12909409403800964

In [39]:
# model evaluate
with torch.no_grad():
  y_pred=model.forward(x_test_tensor.float())

  y_pred=(y_pred>1).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f"accuracy {accuracy}")

accuracy 0.6228070259094238